jomanel_core:
    resource: "@JOMANELCoreBundle/Resources/config/routing.yml"
    prefix:   /



jomanel_platform:
    resource: "@JOMANELPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

