security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        JOMANEL\UserBundle\Entity\User: sha512 #plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username
            #entity:
            #    class:    JOMANEL\UserBundle\Entity\User
            #    property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # On crée un pare-feu uniquement pour le formulaire pour que les anonyme puissent s'identifier
        main_login:
            pattern:   ^/login$ # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            anonymous: true     # On autorise alors les anonymes sur ce pare-feu
        
        # On crée un pare-feu pour le site entier
        main:
            pattern:   ^/
            anonymous: true
            provider:  main # On change cette valeur
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check   #{_locale}
                always_use_default_target_path: true
                default_target_path: jomanel_core_homepage
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter

    access_control:
        - { path: /admin/, roles: ROLE_ADMIN }
