<?php

namespace JOMANEL\PlatformBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository{

 
	public function sortAlphabeticallyQueryBuilder(){//used in advert type
	    return $this
	      ->createQueryBuilder('c')
	      ->orderBy('c.name', 'ASC')
	    ;
  	}

}//fnc
