<?php

namespace JOMANEL\PlatformBundle\Repository;

/**
 * PostTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
